[build]
  base = "rueda-jump-v2"
  command = "npm run build"
  publish = "dist/rueda-jump-v2/browser"

[build.environment]
  NODE_VERSION = "22"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

